env:
  global:
    - CC_TEST_REPORTER_ID=2e4605954b20df1f818519aad3d893d048345c64f74e7338586fdf0331373334
language: python
python:
  - "3.5"
  - "3.7"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -r requirements.txt
script: python3 setup.py pytest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT